let linkedList = require('./LinkedList/LinkedList');
let Stack = require('./Stack/Stack');
let Queue = require('./Queue/Queue');
let BinarySearchTree = require('./BST/BST');

let l1 = new linkedList();
console.log("---------------LinkedList---------------");
console.log(l1.empty());
l1.push_back(1);
console.log(l1.empty());
l1.push_back(2);
l1.push_front(3);
l1.insertAt(0,0);
l1.insertAt(9,0);
l1.insertAt(4,4);
l1.printList();
console.log("find: " +l1.find(4));
l1.pop_front();
l1.printList();
console.log(l1.removeFrom(2));
l1.pop_back();
l1.pop_back();
l1.pop_back();
l1.pop_back();
l1.push_back(1);
l1.push_back(2);
l1.push_front(3);
l1.pop_back();
l1.pop_front();
l1.push_front(3);
l1.pop_back();
l1.push_front(2);
l1.printList();
console.log("size: "+l1.getLength());
console.log("---------------Stack---------------");
let stack = new Stack();
console.log(stack.isEmpty());
stack.push(1);
stack.push(2);
stack.push(3);
stack.push(4);
console.log("removing "+stack.pop()+" from the top of the stack");
console.log(stack.isEmpty());
console.log("Top of stack: "+stack.peek());
stack.printStack();
console.log("size: "+stack.getSize());
console.log("---------------Queue---------------");
let q = new Queue();
console.log(q.isEmpty());
q.enqueue(1);
console.log(q.isEmpty());
q.enqueue(2);
q.enqueue(3);
q.enqueue(4);
q.enqueue(5);
q.enqueue(6);
q.enqueue(7);
q.enqueue(8);
q.enqueue(9);
q.printQueue();
console.log("size: "+q.getSize());
console.log("Front of queue: "+q.front());
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.printQueue();
console.log("size: "+q.getSize());
console.log("Front of queue: "+q.front());
console.log("---------------BST---------------");
let bst = new BinarySearchTree();
bst.insert(7);
bst.insert(9);
bst.insert(2);
bst.insert(11);
bst.insert(5);
bst.insert(1);
bst.insert(10);
bst.remove(9);
console.log(bst.search(10));
console.log(bst.search(4));
console.log(bst);
let bst2 = new BinarySearchTree();
bst2.insert(71);
bst2.insert(92);
bst2.insert(28);
console.log(bst2);
bst2.remove(71);
console.log(bst2.search(28));
console.log(bst2);
console.log(bst2.getRootNode().data);
console.log("-----");
bst.printInOrder();
console.log("-----");
bst.printPreOrder();
console.log("-----");
bst.printPostOrder();
console.log("-----");
console.log("BST height: "+bst.getHeight());
console.log("BST2 height: "+bst2.getHeight());